### ISSUE TITLE
Practica de Realidad aumentada con Heroku

### ISSUE THREAD

**Issue by Christopherg2** [SistemasTecTlaxiaco/practica-de-realidad-aumentada-con-objetos-3d-en-heroku-equipo-damaris#2]
[Practica3 de Realidad aumentada con Heroku.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-realidad-aumentada-con-objetos-3d-en-heroku-equipo-damaris/files/8281370/Practica3.de.Realidad.aumentada.con.Heroku.pdf)

**Comment by NataliaSantiago** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
